export const ETHIOPIAN_BANKS = [
  { label: 'Commercial Bank of Ethiopia (CBE)', value: 'Commercial Bank of Ethiopia (CBE)' },
  { label: 'Awash Bank', value: 'Awash Bank' },
  { label: 'Dashen Bank', value: 'Dashen Bank' },
  { label: 'Bank of Abyssinia', value: 'Bank of Abyssinia' },
  { label: 'Wegagen Bank', value: 'Wegagen Bank' },
  { label: 'Hibret Bank', value: 'Hibret Bank' },
  { label: 'Nib International Bank', value: 'Nib International Bank' },
  { label: 'Cooperative Bank of Oromia', value: 'Cooperative Bank of Oromia' },
  { label: 'Lion International Bank', value: 'Lion International Bank' },
  { label: 'Zemen Bank', value: 'Zemen Bank' },
  { label: 'Oromia International Bank', value: 'Oromia International Bank' },
  { label: 'Buna International Bank', value: 'Buna International Bank' },
  { label: 'Berhan Bank', value: 'Berhan Bank' },
  { label: 'Abay Bank', value: 'Abay Bank' },
  { label: 'Addis International Bank', value: 'Addis International Bank' },
  { label: 'Global Bank Ethiopia', value: 'Global Bank Ethiopia' },
  { label: 'Enat Bank', value: 'Enat Bank' },
  { label: 'ZamZam Bank', value: 'ZamZam Bank' },
  { label: 'Hijra Bank', value: 'Hijra Bank' },
  { label: 'Amhara Bank', value: 'Amhara Bank' },
  { label: 'Goh Betoch Bank', value: 'Goh Betoch Bank' },
  { label: 'Tsehay Bank', value: 'Tsehay Bank' },
  { label: 'Ahadu Bank', value: 'Ahadu Bank' },
  { label: 'Siinqee Bank', value: 'Siinqee Bank' },
  { label: 'Shabelle Bank', value: 'Shabelle Bank' },
  { label: 'Tsedey Bank', value: 'Tsedey Bank' },
  { label: 'Sidama Bank', value: 'Sidama Bank' },
  { label: 'Omo Bank', value: 'Omo Bank' },
  { label: 'Gadaa Bank', value: 'Gadaa Bank' },
  { label: 'National Bank of Ethiopia', value: 'National Bank of Ethiopia' }
];
